---

- name: elastizabbix-configure | Add elastizabbix in /etc/zabbix/scritps
  template:
    src=elastizabbix.j2
    dest=/etc/zabbix/scritps
    owner=zabbix
    group=zabbix
    mode=0777

- name: elastizabbix-configure | Add elastizabbix.conf in /etc/zabbix/conf.d
  copy:
    src=elastizabbix.conf
    dest=/etc/zabbix/conf.d
    owner=root
    group=root
    mode=0644
